import type { ProfileSummary } from "~/types/github";
import { formatDate, formatNumber } from "./format";

/**
 * Generates a printable HTML "developer summary" and triggers download.
 * Users can open the file and use the browser's Print → Save as PDF.
 */
export function downloadSummaryHtml(summary: ProfileSummary) {
  const { user, totalStars, totalForks, languages, topRepos } = summary;
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(user.login)} — Developer Summary</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #0f172a; padding: 48px; max-width: 880px; margin: 0 auto; }
  header { display: flex; gap: 24px; align-items: center; border-bottom: 2px solid #e2e8f0; padding-bottom: 24px; }
  header img { width: 96px; height: 96px; border-radius: 50%; }
  h1 { margin: 0 0 4px; font-size: 28px; }
  h2 { margin-top: 40px; font-size: 20px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
  .muted { color: #64748b; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-top: 24px; }
  .stat { background: #f8fafc; border-radius: 12px; padding: 16px; text-align: center; }
  .stat .v { font-size: 24px; font-weight: 700; }
  .stat .l { color: #64748b; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
  .lang-row { display: flex; align-items: center; gap: 12px; margin: 8px 0; }
  .lang-bar { flex: 1; height: 8px; background: #e2e8f0; border-radius: 999px; overflow: hidden; }
  .lang-bar > span { display: block; height: 100%; }
  .repo { padding: 12px 0; border-bottom: 1px solid #f1f5f9; }
  .repo .name { font-weight: 600; }
  .repo .meta { color: #64748b; font-size: 13px; margin-top: 4px; }
  footer { margin-top: 48px; color: #94a3b8; font-size: 12px; text-align: center; }
  @media print { body { padding: 24px; } }
</style>
</head>
<body>
  <header>
    <img src="${escapeAttr(user.avatar_url)}" alt="" />
    <div>
      <h1>${escapeHtml(user.name ?? user.login)}</h1>
      <div class="muted">@${escapeHtml(user.login)}</div>
      ${user.bio ? `<p style="margin-top:8px">${escapeHtml(user.bio)}</p>` : ""}
    </div>
  </header>
  <div class="stats">
    <div class="stat"><div class="v">${formatNumber(user.public_repos)}</div><div class="l">Repos</div></div>
    <div class="stat"><div class="v">${formatNumber(totalStars)}</div><div class="l">Stars</div></div>
    <div class="stat"><div class="v">${formatNumber(user.followers)}</div><div class="l">Followers</div></div>
    <div class="stat"><div class="v">${formatNumber(totalForks)}</div><div class="l">Forks</div></div>
  </div>
  <h2>Top Languages</h2>
  ${
    languages.length
      ? languages
          .map(
            (l) => `<div class="lang-row">
      <div style="width:120px;font-weight:600">${escapeHtml(l.language)}</div>
      <div class="lang-bar"><span style="width:${l.percentage}%;background:${l.color}"></span></div>
      <div class="muted" style="width:60px;text-align:right">${l.percentage}%</div>
    </div>`,
          )
          .join("")
      : '<p class="muted">No language data.</p>'
  }
  <h2>Top Repositories</h2>
  ${
    topRepos.length
      ? topRepos
          .map(
            (r) => `<div class="repo">
      <div class="name">${escapeHtml(r.name)} — ★ ${formatNumber(r.stargazers_count)}</div>
      ${r.description ? `<div>${escapeHtml(r.description)}</div>` : ""}
      <div class="meta">${r.language ?? "—"} · Updated ${formatDate(r.updated_at)}</div>
    </div>`,
          )
          .join("")
      : '<p class="muted">No public repositories.</p>'
  }
  <h2>Account</h2>
  <p class="muted">Member since ${formatDate(user.created_at)} · <a href="${escapeAttr(user.html_url)}">${escapeAttr(user.html_url)}</a></p>
  <footer>Generated by GitHub Developer Portfolio Analyzer</footer>
</body>
</html>`;
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${user.login}-developer-summary.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => {
    switch (c) {
      case "&": return "&amp;";
      case "<": return "&lt;";
      case ">": return "&gt;";
      case '"': return "&quot;";
      default: return "&#39;";
    }
  });
}
function escapeAttr(s: string): string {
  return escapeHtml(s);
}
